package com.campus.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Optional;

import com.campus.console.StudentMenu;
import com.campus.util.DBConnection;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Student {
    private int studentId;    // auto generated by SQL
    private String name;
    private Optional<String> email;
    private Optional<String> phone;
    private int pin;          // numeric PIN — used for login and to authorise transfers
    private Wallet wallet;    // fetched as object at runtime, not stored inside student in DB

    public String display() {
        return "\n--- Student Details ---" +
               "\nStudent ID : " + studentId +
               "\nName       : " + name +
               "\nEmail      : " + email.orElse("N/A") +
               "\nPhone      : " + phone.orElse("N/A") +
               "\nBalance    : ₹" + (wallet != null ? wallet.getBalance() : "N/A");
    }


}