package com.campus.model;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode

public class Transaction {
    private String txnId;
    private int senderId;
    private int receiverId;
    private double amount;
    private TxnType type;
    private LocalDateTime timestamp;
    private String status;
    // Specific campus-payment category (CANTEEN, LIBRARY, HOSTEL, ...).
    // null for transfers, deposits, withdrawals and split settlements.
    private String category;

    // Constructor, getters, setters, toString, and equals/hashCode are all
    // generated by Lombok (@Data / @AllArgsConstructor / @NoArgsConstructor).
}